### ISSUE TITLE
How to get the same prediction result as contrafold

### ISSUE THREAD

**Issue by farezaur** [keio-bioinformatics/mxfold#1] opened 2019-03-14 02:12 UTC
Hi,

I was trying to reproduce the same results as contrafold with default contrafold parameters in mxfold. Is it possible to do that? I tried doing enabling all the contrafold params flags and setting all the contrafold defined params. The resulting viterbi score is similar but not totally same. Can you tell me if its possible to that and if yes, how will I be able to do that? Thanks in advance.

Thanks
Reza

**Comment by satoken** [comment] 2019-03-19 07:33
Theoretically, it should be possible. However, we haven't tried to perfectly reproduce the same results as the original contrafold with mxfold because it is not an important point in our paper.

**Comment by farezaur** [comment] 2019-03-20 21:37
I could reproduce the result. But I also had to fix a bug in your code. And also change the parameters to contrafold parameters.

For line 413 in InferenceEngine.cpp you should add if(l1<=l2)cache_score_single[l1][l2].first += find_param(params_, fm_->find_internal_explicit(l1, l2));
                else cache_score_single[l1][l2].first += find_param(params_, fm_->find_internal_explicit(l2, l1));

Because for internal explicit it is a symmetric feature.

Thanks
Reza

**Comment by farezaur** [comment] 2019-03-23 00:34
Hi, I have another question. In your paper when you guys mentioned the results for context length L = 3, 4, 5 etc how did you guys train for that. I tried training with only contrafold parameters, but it seems to have trouble with TrainSetA, producing very low accuracy. For TrainSetB the result is good. Is it a problem you guys also faced? 

Basically I want to compare the performance of mxfold and contrafold when they are using same features.

Thanks
Reza

**Comment by satoken** [comment] 2019-03-28 05:59
Hi, Reza,

Thank you for your bug report.
We merged the fix you proposed:

> For line 413 in InferenceEngine.cpp you should add if(l1<=l2)cache_score_single[l1][l2].first += find_param(params_, fm_->find_internal_explicit(l1, l2));
> else cache_score_single[l1][l2].first += find_param(params_, fm_->find_internal_explicit(l2, l1));

**Closed as completed** 2022-02-18 03:40 UTC
